/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as SplatRouteImport } from './routes/$'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as BrowseRouteImport } from './routes/browse'
import { Route as ChatRouteImport } from './routes/chat'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as HowItWorksRouteImport } from './routes/how-it-works'
import { Route as LoginRouteImport } from './routes/login'
import { Route as MyListingsRouteImport } from './routes/my-listings'
import { Route as MyReportsRouteImport } from './routes/my-reports'
import { Route as MyRequestsRouteImport } from './routes/my-requests'
import { Route as PostItemRouteImport } from './routes/post-item'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as ProfileRouteImport } from './routes/profile'
import { Route as RegisterRouteImport } from './routes/register'
import { Route as SafetyRouteImport } from './routes/safety'
import { Route as TermsRouteImport } from './routes/terms'
import { Route as TransactionsRouteImport } from './routes/transactions'
import { Route as VerifyOtpRouteImport } from './routes/verify-otp'
import { Route as ItemsIdRouteImport } from './routes/items.$id'
import { Route as UsersIdRouteImport } from './routes/users.$id'
import { Route as ItemsIdEditRouteImport } from './routes/items_.$id.edit'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const SplatRoute = SplatRouteImport.update({
  id: '/$',
  path: '/$',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const BrowseRoute = BrowseRouteImport.update({
  id: '/browse',
  path: '/browse',
  getParentRoute: () => rootRouteImport,
} as any)
const ChatRoute = ChatRouteImport.update({
  id: '/chat',
  path: '/chat',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const HowItWorksRoute = HowItWorksRouteImport.update({
  id: '/how-it-works',
  path: '/how-it-works',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const MyListingsRoute = MyListingsRouteImport.update({
  id: '/my-listings',
  path: '/my-listings',
  getParentRoute: () => rootRouteImport,
} as any)
const MyReportsRoute = MyReportsRouteImport.update({
  id: '/my-reports',
  path: '/my-reports',
  getParentRoute: () => rootRouteImport,
} as any)
const MyRequestsRoute = MyRequestsRouteImport.update({
  id: '/my-requests',
  path: '/my-requests',
  getParentRoute: () => rootRouteImport,
} as any)
const PostItemRoute = PostItemRouteImport.update({
  id: '/post-item',
  path: '/post-item',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileRoute = ProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const RegisterRoute = RegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => rootRouteImport,
} as any)
const SafetyRoute = SafetyRouteImport.update({
  id: '/safety',
  path: '/safety',
  getParentRoute: () => rootRouteImport,
} as any)
const TermsRoute = TermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const TransactionsRoute = TransactionsRouteImport.update({
  id: '/transactions',
  path: '/transactions',
  getParentRoute: () => rootRouteImport,
} as any)
const VerifyOtpRoute = VerifyOtpRouteImport.update({
  id: '/verify-otp',
  path: '/verify-otp',
  getParentRoute: () => rootRouteImport,
} as any)
const ItemsIdRoute = ItemsIdRouteImport.update({
  id: '/items/$id',
  path: '/items/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const UsersIdRoute = UsersIdRouteImport.update({
  id: '/users/$id',
  path: '/users/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const ItemsIdEditRoute = ItemsIdEditRouteImport.update({
  id: '/items_/$id/edit',
  path: '/items/$id/edit',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/$': typeof SplatRoute
  '/admin': typeof AdminRoute
  '/browse': typeof BrowseRoute
  '/chat': typeof ChatRoute
  '/dashboard': typeof DashboardRoute
  '/how-it-works': typeof HowItWorksRoute
  '/login': typeof LoginRoute
  '/my-listings': typeof MyListingsRoute
  '/my-reports': typeof MyReportsRoute
  '/my-requests': typeof MyRequestsRoute
  '/post-item': typeof PostItemRoute
  '/privacy': typeof PrivacyRoute
  '/profile': typeof ProfileRoute
  '/register': typeof RegisterRoute
  '/safety': typeof SafetyRoute
  '/terms': typeof TermsRoute
  '/transactions': typeof TransactionsRoute
  '/verify-otp': typeof VerifyOtpRoute
  '/items/$id': typeof ItemsIdRoute
  '/users/$id': typeof UsersIdRoute
  '/items/$id/edit': typeof ItemsIdEditRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/$': typeof SplatRoute
  '/admin': typeof AdminRoute
  '/browse': typeof BrowseRoute
  '/chat': typeof ChatRoute
  '/dashboard': typeof DashboardRoute
  '/how-it-works': typeof HowItWorksRoute
  '/login': typeof LoginRoute
  '/my-listings': typeof MyListingsRoute
  '/my-reports': typeof MyReportsRoute
  '/my-requests': typeof MyRequestsRoute
  '/post-item': typeof PostItemRoute
  '/privacy': typeof PrivacyRoute
  '/profile': typeof ProfileRoute
  '/register': typeof RegisterRoute
  '/safety': typeof SafetyRoute
  '/terms': typeof TermsRoute
  '/transactions': typeof TransactionsRoute
  '/verify-otp': typeof VerifyOtpRoute
  '/items/$id': typeof ItemsIdRoute
  '/users/$id': typeof UsersIdRoute
  '/items/$id/edit': typeof ItemsIdEditRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/$': typeof SplatRoute
  '/admin': typeof AdminRoute
  '/browse': typeof BrowseRoute
  '/chat': typeof ChatRoute
  '/dashboard': typeof DashboardRoute
  '/how-it-works': typeof HowItWorksRoute
  '/login': typeof LoginRoute
  '/my-listings': typeof MyListingsRoute
  '/my-reports': typeof MyReportsRoute
  '/my-requests': typeof MyRequestsRoute
  '/post-item': typeof PostItemRoute
  '/privacy': typeof PrivacyRoute
  '/profile': typeof ProfileRoute
  '/register': typeof RegisterRoute
  '/safety': typeof SafetyRoute
  '/terms': typeof TermsRoute
  '/transactions': typeof TransactionsRoute
  '/verify-otp': typeof VerifyOtpRoute
  '/items/$id': typeof ItemsIdRoute
  '/users/$id': typeof UsersIdRoute
  '/items_/$id/edit': typeof ItemsIdEditRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/$'
    | '/admin'
    | '/browse'
    | '/chat'
    | '/dashboard'
    | '/how-it-works'
    | '/login'
    | '/my-listings'
    | '/my-reports'
    | '/my-requests'
    | '/post-item'
    | '/privacy'
    | '/profile'
    | '/register'
    | '/safety'
    | '/terms'
    | '/transactions'
    | '/verify-otp'
    | '/items/$id'
    | '/users/$id'
    | '/items/$id/edit'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/$'
    | '/admin'
    | '/browse'
    | '/chat'
    | '/dashboard'
    | '/how-it-works'
    | '/login'
    | '/my-listings'
    | '/my-reports'
    | '/my-requests'
    | '/post-item'
    | '/privacy'
    | '/profile'
    | '/register'
    | '/safety'
    | '/terms'
    | '/transactions'
    | '/verify-otp'
    | '/items/$id'
    | '/users/$id'
    | '/items/$id/edit'
  id:
    | '__root__'
    | '/'
    | '/$'
    | '/admin'
    | '/browse'
    | '/chat'
    | '/dashboard'
    | '/how-it-works'
    | '/login'
    | '/my-listings'
    | '/my-reports'
    | '/my-requests'
    | '/post-item'
    | '/privacy'
    | '/profile'
    | '/register'
    | '/safety'
    | '/terms'
    | '/transactions'
    | '/verify-otp'
    | '/items/$id'
    | '/users/$id'
    | '/items_/$id/edit'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  SplatRoute: typeof SplatRoute
  AdminRoute: typeof AdminRoute
  BrowseRoute: typeof BrowseRoute
  ChatRoute: typeof ChatRoute
  DashboardRoute: typeof DashboardRoute
  HowItWorksRoute: typeof HowItWorksRoute
  LoginRoute: typeof LoginRoute
  MyListingsRoute: typeof MyListingsRoute
  MyReportsRoute: typeof MyReportsRoute
  MyRequestsRoute: typeof MyRequestsRoute
  PostItemRoute: typeof PostItemRoute
  PrivacyRoute: typeof PrivacyRoute
  ProfileRoute: typeof ProfileRoute
  RegisterRoute: typeof RegisterRoute
  SafetyRoute: typeof SafetyRoute
  TermsRoute: typeof TermsRoute
  TransactionsRoute: typeof TransactionsRoute
  VerifyOtpRoute: typeof VerifyOtpRoute
  ItemsIdRoute: typeof ItemsIdRoute
  UsersIdRoute: typeof UsersIdRoute
  ItemsIdEditRoute: typeof ItemsIdEditRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$': {
      id: '/$'
      path: '/$'
      fullPath: '/$'
      preLoaderRoute: typeof SplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/browse': {
      id: '/browse'
      path: '/browse'
      fullPath: '/browse'
      preLoaderRoute: typeof BrowseRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/chat': {
      id: '/chat'
      path: '/chat'
      fullPath: '/chat'
      preLoaderRoute: typeof ChatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/how-it-works': {
      id: '/how-it-works'
      path: '/how-it-works'
      fullPath: '/how-it-works'
      preLoaderRoute: typeof HowItWorksRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/my-listings': {
      id: '/my-listings'
      path: '/my-listings'
      fullPath: '/my-listings'
      preLoaderRoute: typeof MyListingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/my-reports': {
      id: '/my-reports'
      path: '/my-reports'
      fullPath: '/my-reports'
      preLoaderRoute: typeof MyReportsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/my-requests': {
      id: '/my-requests'
      path: '/my-requests'
      fullPath: '/my-requests'
      preLoaderRoute: typeof MyRequestsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/post-item': {
      id: '/post-item'
      path: '/post-item'
      fullPath: '/post-item'
      preLoaderRoute: typeof PostItemRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile': {
      id: '/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof ProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/register': {
      id: '/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof RegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/safety': {
      id: '/safety'
      path: '/safety'
      fullPath: '/safety'
      preLoaderRoute: typeof SafetyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/terms': {
      id: '/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/transactions': {
      id: '/transactions'
      path: '/transactions'
      fullPath: '/transactions'
      preLoaderRoute: typeof TransactionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/verify-otp': {
      id: '/verify-otp'
      path: '/verify-otp'
      fullPath: '/verify-otp'
      preLoaderRoute: typeof VerifyOtpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/items/$id': {
      id: '/items/$id'
      path: '/items/$id'
      fullPath: '/items/$id'
      preLoaderRoute: typeof ItemsIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/users/$id': {
      id: '/users/$id'
      path: '/users/$id'
      fullPath: '/users/$id'
      preLoaderRoute: typeof UsersIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/items_/$id/edit': {
      id: '/items_/$id/edit'
      path: '/items/$id/edit'
      fullPath: '/items/$id/edit'
      preLoaderRoute: typeof ItemsIdEditRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  SplatRoute: SplatRoute,
  AdminRoute: AdminRoute,
  BrowseRoute: BrowseRoute,
  ChatRoute: ChatRoute,
  DashboardRoute: DashboardRoute,
  HowItWorksRoute: HowItWorksRoute,
  LoginRoute: LoginRoute,
  MyListingsRoute: MyListingsRoute,
  MyReportsRoute: MyReportsRoute,
  MyRequestsRoute: MyRequestsRoute,
  PostItemRoute: PostItemRoute,
  PrivacyRoute: PrivacyRoute,
  ProfileRoute: ProfileRoute,
  RegisterRoute: RegisterRoute,
  SafetyRoute: SafetyRoute,
  TermsRoute: TermsRoute,
  TransactionsRoute: TransactionsRoute,
  VerifyOtpRoute: VerifyOtpRoute,
  ItemsIdRoute: ItemsIdRoute,
  UsersIdRoute: UsersIdRoute,
  ItemsIdEditRoute: ItemsIdEditRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
